version: 3

tasks:
  CI:
    deps:
      - test:doc
      - test:default
      - for:  [tokio, async-std, smol, glommio]
        task: test:rt
        vars: { rt: '{{.ITEM}}' }
      - task: bench
        vars: { flag: '--no-run' }

  test:doc:
    cmds:
      - cargo test --doc --features sse,ws,http1,rt_tokio

  test:default:
    cmds:
      - cargo test --lib
      - cargo test --lib --features sse

  test:rt:
    cmds:
      - cargo test --lib --features rt_{{.rt}},ws
      - cargo test --lib --features rt_{{.rt}},http1
      - cargo test --lib --features rt_{{.rt}},sse,ws,http1

  bench:
    cmds:
      - cargo version | grep -q 'nightly' && cargo bench {{.flag}}
