version: '3'

tasks:
  CI:
    deps:
      - test:default
      - test:rt
      - test:doc
      - bench

  test:default:
    cmds:
      - cargo test --lib
      - cargo test --lib --features sse

  test:rt:
    vars:
      rt: ['tokio', 'async-std', 'smol', 'glommio']
    cmds:
      - for: { var: rt }
        cmd: cargo test --lib --features rt_{{.ITEM}},ws
      - for: { var: rt }
        cmd: cargo test --lib --features rt_{{.ITEM}},http1
      - for: { var: rt }
        cmd: cargo test --lib --features rt_{{.ITEM}},sse,ws,http1

  test:doc:
    cmds:
      - cargo test --doc --features sse,ws,http1,rt_tokio

  bench:
    cmds:
      - cargo version | grep -q 'nightly' && cargo bench
