name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Taskfile
        run:  |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task CI
